Awesome books project!
denisdiaconu/awesome_books pull request #1
Opened 2021-07-05 17:12 UTC by denisdiaconu

In this project, we built a basic website that allows users to add/remove books from a list.

2021-07-05 18:01 UTC, sinansevgi reviewed
Hi @denisdiaconu and @TSHEPO-CLOUD , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a descriptive README file. Please also remove the node_modules folder and add files that are not related to the project to the .gitignore file


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-07-05 18:58 UTC, vichuge requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi dear student, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your README and PR message are descriptive ✔️

## Aspects to improve ♻️

- [ ] Check the comments under the review.

- After fixing the button, the next CR could be able to test all other points of the project.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, consider:
- [OPTIONAL]

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-05 18:58 UTC, vichuge commented on index.html
> +      <button type="button" id="btn">Add</button>
- [ ] When I click the add button on deployment it doesn't work, I kindly invite you to fix it. 🐶 
- Hint: I'm almost sure the problem is on the src script, check it out.
![image](https://user-images.githubusercontent.com/20563252/124510146-da2bc080-dd98-11eb-92dd-b8b7c6e5cd6e.png)

2021-07-06 07:33 UTC, denisdiaconu commented
Hello!
We fixed all the last code reviewer requesets.

2021-07-06 09:13 UTC, mikenath223 requested changes
Hi there, 

Awesome job on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. Let's work on those.


 ## Required Changes ♻️
_Kindly check the comments under the review._
- [ ] Update eslintrc.json to reflect the correct linting rules.
- [ ] Avoid disabling the entire eslint check for a section.


Happy coding, Cheers!🚀🚀

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, whether it's valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-06 09:15 UTC, mikenath223 commented on src/js/index.js
> +/* eslint-enable */
- [ ] Kindly avoid disabling the entire eslint rule. To improve the professionalism of your project consider fixing the linting issue or simply disable the specific rule.

2021-07-06 09:17 UTC, mikenath223 commented on package.json
> +    "eslint-plugin-import": "^2.23.2",
- [ ] Ensure you use the same eslint config [rules](https://github.com/microverseinc/linters-config/blob/master/javascript/.eslintrc.json) shared by other students. To update the rules consider raising a PR.

2021-07-06 10:34 UTC, denisdiaconu commented
Update eslintrc.json to have the same config rules shared by other students.
Remove disabled eslint inside the js file.
Fix linters errors.

2021-07-06 10:37 UTC, mikenath223 approved these changes
Hello there  

Your project is complete!  There is nothing else to say other than... it's time to merge it 🛳 
Congratulations! 🎉 

Happy coding. Cheers! 🚀🚀

If you feel something isn't clear enough you can leave a question or comment in the PR thread.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-06 10:39 UTC, merged