Change the objects and arrays into classes
denisdiaconu/awesome_books pull request #2
Opened 2021-07-06 17:08 UTC by denisdiaconu

In this project, we refactor the Awesome books application to use JavaScript classes.

2021-07-06 18:20 UTC, smcommits requested changes
Hi @denisdiaconu,  

### You have done an excellent job. The project appears to be fantastic. It reflects great efforts and good understanding. 
### To make this project even better, there are some issues that you still need to work on. You are almost there!


 ## Required Changes ♻️
_Please check the inline comments below._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-06 18:20 UTC, smcommits commented on src/js/index.js
> +class Ls {
- [ ] **The newly added book disappears when the page is refreshed. Please fix this.**

When I add a book, the data is persisted in the local storage. Great job with that. However, the book disappears from the page when I refresh it. Please fix it. 

![a](https://user-images.githubusercontent.com/59168430/124647903-2ddefc80-deb4-11eb-93a3-3bceb4619316.gif)

2021-07-06 18:20 UTC, smcommits commented on src/js/index.js
> +class Ls {
- [ ] **[OPTIONAL] Please consider using more descriptive names in your code.**

The name `Ls` makes it difficult to understand the code. You can name the class something like `Books` for example.

2021-07-07 08:16 UTC, denisdiaconu commented
The newly added book is now appearing when the page is refreshed.

2021-07-07 08:28 UTC, de-scholar approved these changes
Hi @denisdiaconu , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-07 17:57 UTC, de-scholar approved these changes
Hi @denisdiaconu and @TSHEPO-CLOUD , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-09 07:00 UTC, merged